### ISSUE TITLE
Still builds AspNetCore module into web.config

### ISSUE THREAD

**Issue by robertmclaws** [DamianEdwards/SystemWebSdk#2]
I have a project using this, and we got it to a point where it would build and deploy in Azure DevOps. The packaged artifact still has 2 aspNetCoreModules referenced in the web.config.

Example:

```
  <system.webServer>
    <modules>
      <remove name="WebDAVModule" />
      <remove name="FormsAuthentication" />
    </modules>
    <handlers>
      <remove name="WebDAV" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <validation validateIntegratedModeConfiguration="false" />
    <aspNetCore processPath="dotnet" arguments=".\CloudNimble.Alexis.RestService.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
```

This happens whether you use `dotnet publish` or the VS Build task.

**Comment by DamianEdwards** [comment]
Yep. For now, I made the sample work by [including that section but nulling out the path](https://github.com/DamianEdwards/SystemWebSdk/blob/master/WebApiSdk/Web.config#L17). If the section is there, the publish/build task shouldn't alter it.

My assumption when an actual SystemWebSdk is made, it wouldn't be based on the existing Web.Sdk and wouldn't bring this target over.

**Comment by robertmclaws** [comment]
OH! That's hacky but wicked-smart. Much easier than manipulating the file after the fact. Thanks!
